---
deployment:
  tasks:
    - cd $REPO_PATH
    - export NODE_VERSION=18  # Change this to your Node.js version on cPanel
    - export DEPLOY_PATH=/home/kliconlinemedia@gmail.com/public_html
    - /opt/cpanel/ea-nodejs18/bin/npm install  # Ensure you're using the right Node version
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - /bin/cp -r .next/standalone/* $DEPLOY_PATH
    - /bin/cp -r .next/static $DEPLOY_PATH/.next/static
